config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show, :index]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'
  
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients do
    resources :appointments #(shallow: true)
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews
  end
  
  resources :reviews
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/treatment.rb
class Treatment < ApplicationRecord

    has_many :appointments
    has_many :clients, through: :appointments 
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

    def index 
        @treatment = Treatment.all
    end 

    def new 
        @treatment = Treatment.new  
    end 

    def create
        @treatment = Treatment.new(treatment_params)
        if @treatment.save 
            redirect_to @treatment
        else 
            render :new 
        end 
    end 

    def show
        @treatment = Treatment.find(params[:id])
    end 

   
    private 

    def treatment_params
        params.require('treatment').permit(:title, :price, :duration, :description)
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/index.html.erb
<br><br><br>
    <div class="container">
        <div class="row justify-content-center">
            <h1>OUR TREATMENTS</h1>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <% Treatment.all.each do |treatment| %>
                <ul>
                    <%= link_to treatment.title, treatment_path(treatment) %></a>
                </ul>
            <% end %>
        </div>
    </div>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <img src="/assets/massage.jpg" class="float-left" alt="Paris" width="390" height="300"> 
            </div>
            <div class="col-sm-4">
                <img src="/assets/wood_therapy.jpeg" class="float-right" width="450" height="300">
            </div>
            <div class="col-sm-4">
                <img src="/assets/facial_1.jpeg" class="float-right" alt="Paris" width="400" height="300">
            </div>
        </div>
    </div>
<br>

    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <img src="/assets/spa_tub.JPG" class="mx-auto d-block" style="width:50%">
            <h4></h4>
            <p>Exclusive beauty and wellness, treatments with trusted hands bring locals together for the most lux lifestyle trends.</p>
            <p> Our handcrafted practices, focuses on the healing properties of Sea, Salt, Sand, and Sound.
                Sea promises an escape from reality with blue mineral oils that help muscles relax and heal.
                Salt balances energy with well-being properties that calm nerves and soothe muscles.
                Sand warms the body for decadent comfort while stimulating the skin’s reflexes.
                Sound from Tingsha bells set the tempo for the ultimate balance of mind, body, and soul.
            </p>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <a class="btn btn-secondary" <%= link_to "Book a Appointment »", new_appointment_path %></a>
        </div>
    </div>
</div>

app/views/treatments/new.html.erb
<br><br><br>

<h1>Creating New Treatment</h1>

<%= form_for(@treatment) do |f| %>

<br><br>
<%= f.label :title %>
<%= f.text_field :title, required:true %>
<br><br>
<%= f.label :price %>
<%= f.text_field :price, required:true %>

<br><br>
<%= f.label :duration %>
<%= f.text_field :duration, required:true %>

<br><br>
<%= f.label :description %>
<%= f.text_field :description, required:true %>

<br><br>
<%= f.submit 'request treatment' %>
<% end %>

app/views/treatments/show.html.erb
<br><br><br>

    <div class="container">
        <div class="row">
            <ul>
                <h4><%= @treatment.title %></h4> <br>
                <%= @treatment.price %> |
                <%= @treatment.duration %> <br>
                <%= @treatment.description %> <br><br><br>
                <%= image_tag '/assets/treat_baner.jpg' %>
            </ul>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <a class="btn btn-secondary" <%= link_to "Book a Appointment »", new_appointment_path %></a>
            </div>
        </div>
    </div>
<br>
      <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4">
                <img src="/assets/salt_facial.jpg" class="float-left" alt="Paris" width="390" height="300"> 
            </div>
            <div class="col-sm-4">
                <img src="/assets/lashes_2.jpeg" class="float-right" width="450" height="300">
            </div>
            <div class="col-sm-4">
                <img src="/assets/sand.jpg" class="float-right" alt="Paris" width="400" height="300">
            </div>
        </div>
    </div>

    