config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show, :index]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'
  
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients do
    resources :appointments #(shallow: true)
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews
  end
  
  resources :reviews
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

    has_secure_password

    has_many :reviews
    has_many :appointments
    has_many :treatments, through: :appointments 
    has_many :reviewed_appointments, through: :reviews, source: :appointments 


    validates_presence_of :first_name, :last_name, format: { with: /\A[a-zA-Z]+\Z/ }, message:"Cannot be blank"
    validates_numericality_of :phone, on: :create
    validates :email, format: {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, uniqueness: {message:"already belongs to an existing account"}

    
   
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    
    before_action :is_logged_in?
    before_action :session_already_set, only: %i[new create]

    def index
       @clients = Client.all
    end

    def new 
        @client = Client.new
    end 

    def create 
        @client = Client.new(client_params)
        if @client.save 
            session[:client_id] = @client.id
            redirect_to @client
        else 
            flash[:message] = "Invalid registration info, please try again"
            render :new 
        end 
    end 

    def show 
        @client = Client.find_by_id(params[:id])
        if current_client != @client
            redirect_to '/'
        end 
    end 

    private

    def client_params
        params.require('client').permit(:first_name, :last_name, :password,:phone,:email)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/index.html.erb
<br><br><br><br><br><br>

<% title "Clients" %>

    <%= content_tag :div, class:"col-md-9" do %>
        <%= render 'layouts/flash_message' %>
    <% end %>

<ul>
    <% @clients.each do |client| %>
    <li><%= link_to client.first_name, client_appointments_path(client) %></li>
    <% end %>
</ul>

app/views/clients/new.html.erb
<%= render partial: "layouts/errors", locals: {object: @client} %>

<div class="container mt-5">
    <div class="card bg-info">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Register</h4>
            <p class="text-center">Get started with your account</p>
        
    
            <%= form_for :client do %>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                </div>
                <input id="client_first_name" name="client[first_name]" class="form-control" placeholder="First name" type="text">
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                </div>
                <input id="client_last_name" name="client[last_name]" class="form-control" placeholder="Last name" type="text">
            </div> 
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                </div>
                <input id="client_email" name="client[email]" class="form-control" placeholder="Email address" type="email">
            </div>
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
                </div>
                <select class="custom-select" style="max-width: 120px;">
                    <option selected="">+1</option>
                    <option value="1">+876</option>
                </select>
                <input id="client_phone" name="client[phone]" class="form-control" placeholder="Phone number" type="number">
            </div> 
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                </div>
                <input id="client_password" name="client[password]"class="form-control" placeholder="Create password" type="password">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Register Account  </button>
            </div>    
            <p class="text-center">Have an account? <%= link_to "Login", login_path %></p>                                                                 
            <% end %>
        </article>
    </div> 
</div>

app/views/clients/show.html.erb
<br><br><br><br><br>

<%= content_tag :div, class:"col-md-9" do %>
  <%= render 'layouts/flash_message' %>
  <% end %>
  
    <div class="container mt-5">
        <div style="background: url(<%= asset_path('blue_bg.jpg') %>)" class="page-holder bg-cover">
            <article class="card-body mx-auto" style="max-width: 400px max-height: 800px;">
                <h2 class="card-title mt-3 text-center"><%= current_client.first_name %></h2>
                <h3><%= display_appointments %></h3>
                
                    <ul>
                        <% @client.appointments.each do |appointment| %>
                        <li><%= link_to appointment.treatment.title, client_appointment_path(@client,appointment) %></li>
                        <% end %>
                    </ul>
                    <br><br>
                    <h5 class="card-title mt-3 text-center">We are looking forward to servicing you!!!</h5>
                    <div class="container mt-5">
                        <div class="row">
                            <div class="col-lg-4">
                                <a class="btn btn-secondary" <%= link_to "Book a New Appointment »", new_appointment_path %></a>
                            </div>
                        </div>
                    </div>
            </article>
        </div>
    </div>
   