config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show, :index]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'
  
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients do
    resources :appointments #(shallow: true)
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews
  end
  
  resources :reviews
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    
    belongs_to :client
    belongs_to :treatment
    has_many :reviews
    has_many :clients, through: :reviews
    
    validates :treatment, :desired_time, :desired_date, presence: true


    validate :desired_date_cannot_be_in_the_past
 
    def desired_date_cannot_be_in_the_past
        if desired_date.present? && desired_date < Date.today
            errors.add(:desired_date, "can't be in the past")
        end
    end 




    scope :alpha, -> { order(:desired_date) }
    # scope :most_booked_treatments, -> {left_joins(:treatments).group('appointments.id').order('count(treatments.appointment_id) desc')}
    
    #accepts_nested_attributes_for 
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :login_required
  
    def index
      if params[:client_id]
        client = Client.find_by(id:params[:client_id])
      if current_client == client
        @appointments = client.appointments.alpha
      else
        flash[:alert] = "Client not found."
        redirect_to clients_path
      end
      # else
      #   @appointments = Appointment.all
      end
    end

    def show
      if params[:client_id]
        client = Client.find_by(id:params[:client_id])
        @appointment = client.appointments.find_by(id:params[:id])
      if !@appointment
        flash[:alert] = "Appointment not found."
        redirect_to client_appointments_path(client)
      end
      else
        @appointment = Appointment.find(params[:id])
      end
    end

    def new 
      @appointment = Appointment.new 
    end 

    def create 
      @appointment = current_client.appointments.build(appointment_params)
      if @appointment.save 
        redirect_to @appointment
      else 
        render :new 
      end 
    end 

    def edit
      if params[:client_id]
        client = Client.find_by(id:params[:client_id])
      if client
        @appointment = client.appointments.find_by(id:params[:id])
        redirect_to client_appointments_path(client) if !@appointment
      else
        redirect_to clients_path, alert: "Client not found"
      end
      else
        @appointment = Appointment.find(params[:id])
      end
    end

    def update 
      @appointment = Appointment.find(params[:id])
      @appointment.update(appointment_params)
      if @appointment.save
        redirect_to @appointment
      else
        render :edit
      end
    end 
  
    def destroy 
      @appointment = Appointment.find_by_id(params[:id])
      if is_logged_in? 
        @appointment = current_client.appointments.find_by_id(params[:id])
        if @appointment
          @appointment.destroy
          flash[:message] = "Your appointment was deleted."
          redirect_to client_appointments_path(current_client)  
        else
          flash[:message] = "Unable to delete this appointment since it doesn't belong to you."
          redirect_to "/"
        end
      else
        flash[:message] = "You need to be logged in first to access this page."
        redirect_to "/login"
      end
    end
    
    private 

    def appointment_params
        params.require('appointment').permit(:special_request, :desired_time, :desired_date, :client_id, :treatment_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
    
    def display_appointments 
        if @client.appointments.empty?
            content_tag(:h5, link_to('No appointments yet - Book an Appointment here', new_appointment_path))
        else
            client = @client == current_client ? 'You have' : "#{@client.first_name}'s"
            content_tag(:h4, "#{client} #{pluralize(@client.appointments.count, 'booked Appointments')}:")
        end
    end

    def last_updated(appointment)
        appointment.updated_at.strftime("Last updated on %A, %B %d, %Y, at %I:%M %p")
    end

    def display_date(d)
        d.strftime('%A, %B %d, %Y')
    end
    
    def display_time(d)
        d.strftime('%I:%M %p')
    end
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>

<br><br>
<%= f.label :desired_date %>
<%= f.date_field :desired_date, required:true %>

<br><br>
<%= f.label :desired_time %>
<%= f.time_field :desired_time, required:true %>


<br><br>
<%= f.label :treatment %>
<%= f.collection_select :treatment_id, Treatment.all, :id, :title %> 

<br><br>
<%= f.label :special_request %>
<%= f.text_field :special_request %>

<br><br>
<%= f.submit 'request appointment' %>
<% end %>

app/views/appointments/edit.html.erb
<br><br><br><br>

    <div class="container mt-5">
        <div style="background: url(<%= asset_path('blue_bg.jpg') %>)" class="page-holder bg-cover">
            <article class="card-body mx-auto" style="max-width: 400px;">
                <h3 class="card-title mt-3 text-center">Edit Appointment Details</h3>
                
                    <%= render partial: "layouts/errors", locals: {object: @appointment} %>
                    <%= render partial: "form" %>

            </article>
        </div>
    </div>

app/views/appointments/index.html.erb
<br><br><br>

    <% if current_client %>
    <div class="container mt-5">
        <div style="background: url(<%= asset_path('blue_bg.jpg') %>)" class="page-holder bg-cover">
            <article class="card-body mx-auto" style="max-width: 400px max-height: 800px;">
                <h2 class="card-title mt-3 text-center">Upcoming Appointments for <%= current_client.first_name %></h2>
                
                    <ul>
                            <% current_client.appointments.each do |appointment| %>
                        <li>
                            <%= link_to appointment.treatment.title, appointment_path(appointment) %> 
                        </li>
                            <% end %>
                        <br><br>
                        <h5 class="card-title mt-3 text-center">We are looking forward to servicing you!!!</h5>
                    </ul>
                    <div class="container mt-5">
                        <div class="row">
                            <div class="col-lg-4">
                                <a class="btn btn-secondary" <%= link_to "Book a New Appointment »", new_client_appointment_path %></a>
                            </div>
                        </div>
                    </div>
            </article>
        </div>
    </div>

    <% end %>

app/views/appointments/new.html.erb
<br><br><br>

    <div class="container mt-5">
        <div style="background: url(<%= asset_path('blue_bg.jpg') %>)" class="page-holder bg-cover">
            <article class="card-body mx-auto" style="max-width: 400px;">
                <h3 class="card-title mt-3 text-center">Request Appointment</h3>

                    <%= render partial: "layouts/errors", locals: {object: @appointment} %>
                    <%= render partial: "form", locals: {appointment: @appointment} %>

            </article>
        </div>
    </div>

app/views/appointments/show.html.erb
<br><br><br>

<div class="container mt-5">
    <div style="background: url(<%= asset_path('blue_bg.jpg') %>)" class="page-holder bg-cover">
        <article class="card-body mx-auto" style="max-width: 400px max-height: 800px;">
            <h2 class="card-title mt-3 text-center">Appointment Details</h2>
            <ul>
                <h4><%= @appointment.treatment.title %></h4>
                <h5><%= @appointment.desired_date.strftime("on %b/%d/%Y") %></h5>
                <h5><%= @appointment.desired_time.strftime("at %I:%M%p") %> </h5>
                <h5><%= @appointment.special_request %></h5> <br>
                <p><%= last_updated @appointment %></p>
                <br><br>
                <h5 class="card-title mt-3 text-center">We are looking forward to servicing you!!!</h5>
            </ul>   
        </article>
    </div>
</div>

<%= render partial: "layouts/errors", locals: {object: @appointment} %>

<div class="container mt-3">
    <% if @appointment.client == current_client %>
        <h6>
        <%= link_to "Edit Appointment", edit_appointment_path(@appointment)%> |
        <%= link_to "Delete Appointment", @appointment, method: :delete, data: { confirm: "Are you sure?" } %>
        </h6>
    <% end %>
</div>