config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'sessions#home', as: 'root', controller: 'sessions'

  get '/register', to: 'clients#new', as: 'register'
  resources :clients, only: [:create], path: 'register'
  resources :clients, only: [:show, :index]
  
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/:provider/callback', to: 'sessions#google'
  
  resources :treatments, only: [:index, :show] do 
    resources :appointments, only: [:index, :show]
  end 

  resources :clients do
    resources :appointments #(shallow: true)
  end 

  resources :appointments
  
  resources :appointments do
    resources :reviews
  end
  
  resources :reviews
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
 
    <% if object.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
          <ul>
            <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
            <% end %>
          </ul>
      </div>
    <% end %>

    

app/views/layouts/_flash_message.erb
<% if flash[:error] %>
    <div class="alert alert-danger" >
        <%=flash[:error]%>
    </div>
<% end %>

<% if flash[:success] %>
    <div class="alert alert-success">
        <%=flash[:success]%>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
    
    <div class="footer-copyright expand-lgpy-5 w-100">
        <div class="container text-center">
            Oasis © <%=Date.today.year%>
        </div>
    </div>

app/views/layouts/_main_container.html.erb
    <div class="<%= yield :main_col_class %>">
        <%= yield :err %>
        <div class="card bg-transparent border-0">
        <div class="card-header text-light border-0 form-transparent">
            <%= yield :card_header %>
        </div>
            <%= yield :card_body %>
            <%= yield :card_footer %>
        </div>
    </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <div class="navbar-brand" 
            <%= link_to 'Oasis', root_path %>
        </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title><%= yield :title %> | Oasis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <link href="carousel.css" rel="stylesheet">
  </head>
    <body>
      <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="/">Oasis</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    <% if !session.has_key?(:client_id) %>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/register">Register</a>
            </li>
            <li class="nav-item">
              <a href="/auth/google_oauth2" class="btn btn-block btn-google"><i class="fab fa-google"></i></a>
            </li>
          </ul>
      </nav>
      
    <% else %>
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item">
						<a class="nav-link" <%= link_to "Appointments", client_appointments_path(current_client) %></a>
					</li>
          <li class="nav-item">
						<a class="nav-link" <%= link_to "Treatments", treatments_path %></a>
					</li>
          <li class="nav-item">
						<a class="nav-link" <%= link_to "New Appointment", new_appointment_path %></a>
					</li>
          <li class="nav-item">
						<a class="nav-link" <%= link_to "Reviews", reviews_path %></a>
					</li>
          <li class="nav-item">
            <a class="nav-link"<%= link_to('Logout', logout_path, method: :delete) %></a>
          </li>
        </ul>
      </nav>
    <% end %>
    </header>
      <br><br><br>

        <%= content_tag :div, class:"col-lg-5 col-xl-6" do %>
          <%= render 'layouts/flash_message' %>
        <% end %>

    <%= yield %>

        <br><br>
   
        <%= content_tag :footer, class:footer_class do %>
          <%= render 'layouts/footer' %>
        <% end %>
        

  </body>
</html>